version: "3.9"  
services:
  ansible:
    build: 
      context: ./ansible_base
      dockerfile: Ansible_Dockerfile
    container_name: ansible_controller
    volumes:
      - type: bind
        source: ./ansible_files
        target: /home/ansible_controller/ansible_files
  hello-devops:
    build: 
      context: ./ansible_base
      dockerfile: Hello_Devops_Dockerfile
    ports:
     - "3000:3000"
    container_name: ansible_target1
